<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Offline POS devices.
 *
 * Every Windows installation of the offline POS registers here and gets an
 * `api_token` it must present on every sync call. `device_id` is generated by
 * the installation itself (SC-POS-KBL-8F31A7) and never changes — not across
 * app updates, not across restores. Server-side ids are still used internally,
 * but nothing about synchronization depends on the local auto-increment id.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('pos_devices')) {
            return;
        }

        Schema::create('pos_devices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->unsignedBigInteger('branch_id')->nullable()->index();

            // Human/ops identity
            $table->string('device_id')->unique();          // SC-POS-KBL-8F31A7
            $table->string('uuid')->unique();               // server-side global id
            $table->string('name');
            $table->string('platform')->default('windows');
            $table->string('app_version')->nullable();
            $table->string('os_version')->nullable();

            // Lifecycle: pending → active → disabled | revoked
            $table->string('status')->default('pending')->index();
            $table->string('activation_code_hash')->nullable();
            $table->timestamp('activation_expires_at')->nullable();
            $table->string('notes')->nullable();

            // Credentials (never stored in clear text)
            $table->string('api_token_hash', 128)->nullable()->index();
            $table->timestamp('token_issued_at')->nullable();
            $table->timestamp('token_rotated_at')->nullable();
            $table->timestamp('token_last_used_at')->nullable();

            // Heartbeat / sync bookkeeping
            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('last_sync_at')->nullable();
            $table->timestamp('last_pull_at')->nullable();
            $table->unsignedBigInteger('last_pull_seq')->default(0);
            $table->unsignedInteger('pending_count')->default(0);
            $table->unsignedInteger('failed_count')->default(0);
            $table->json('last_error')->nullable();
            $table->string('last_ip')->nullable();

            $table->timestamp('registered_at')->nullable();
            $table->foreignId('registered_by')->nullable();
            $table->timestamp('disabled_at')->nullable();
            $table->timestamp('revoked_at')->nullable();
            $table->string('revoked_reason')->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['company_id', 'status']);
            $table->index(['company_id', 'branch_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pos_devices');
    }
};
